services:
  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"      # PHOENIX_PORT
      - "4317:4317"      # PHOENIX_GRPC_PORT
      - "9090:9090"      # [Opcional] Porta do Prometheus se ativada
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - ./data:/mnt/data
